Update for aragonUI 1.0
AutarkLabs/about pull request #41
Opened 2019-12-20 01:53 UTC by chadoh

This fixes some quick things that caused deprecation warnings or had an ugly UI after the update to aragonUI 1.0

It also updates some extra dependencies

2019-12-20 20:29 UTC, PeterMPhillips requested changes
Looks good except the codemirror version

2019-12-20 20:29 UTC, PeterMPhillips commented on app/package.json
> +    "codemirror": "^6.0.0",
This needs to be fixed:
```suggestion
    "codemirror": "^5.50.0",
```

2019-12-20 22:17 UTC, e18r submitted a review, later dismissed
LGTM

2019-12-21 01:55 UTC, PeterMPhillips commented
Closed because most of the commits were accidentally merged directly into `master`. For everything else, PR #44 covers it

2019-12-21 01:55 UTC, closed without merging