No data view
AutarkLabs/about pull request #43
Opened 2019-12-20 21:57 UTC by e18r

Fixes autarklabs/open-enterprise#1713

![Screenshot from 2019-12-20 16-53-18](https://user-images.githubusercontent.com/16065447/71295394-ad948d00-2349-11ea-9335-3acc3dcbaf15.png)

2019-12-20 22:39 UTC, PeterMPhillips requested changes
Looks good! The only issue I have is the assumption that `entries = undefined` we should set the default entries value to an empty array on line 35: `const { entries = [] } = appState` and then make the following changes:

2019-12-20 22:39 UTC, PeterMPhillips commented on app/src/App.js
> +            entries !== undefined &&
```suggestion
            entries.length !== 0 &&
```

2019-12-20 22:39 UTC, PeterMPhillips commented on app/src/App.js
> +            entries !== undefined &&
```suggestion
            entries.length !== 0 &&
```

2019-12-20 22:39 UTC, PeterMPhillips commented on app/src/App.js
> +  if (!entries) {
```suggestion
  if (entries.length === 0) {
```

2020-01-03 21:25 UTC, chadoh requested changes
A couple things to clean up here

2020-01-03 21:25 UTC, chadoh commented on app/src/App.js
> +  const SideContent = () => (
I've seen lots of problems caused by defining components within other components.

Every time React renders `App`, it's going to redefine `SideContent`, and that means that all elements rendered as part of SideContent will be removed from the DOM and re-added. This is incredibly inefficient and can cause big UX problems – in Projects, we had a spot where an input was removed from the DOM and re-added after every keystroke! For the user, this meant that the input lost focus every time they typed a character in it! Incredibly frustrating.

I get that it's tempting to do this. We don't have to pass in any props! But the tradeoffs are almost never worth it.

2020-01-03 21:25 UTC, chadoh commented on app/src/App.js
> +  height: 95vh;
Where does 95 come from? What takes up the other 5?

2020-01-08 17:54 UTC, chadoh requested changes
I pushed my own commit with some cleanup I wanted to see – see obsolete comments below.

I noticed one other thing I'd like us to address now if we can. Does it seem like the side panel is opening too fast? The animation of the background fading happens much more slowly than the side panel opening. See GIF:

![side panel opening too fast](https://user-images.githubusercontent.com/221614/72002728-f6878500-3215-11ea-92ba-90fb782d1bdf.gif)

2020-01-08 17:54 UTC, chadoh commented on app/src/App.js
> +                  members of your organization.
I vote we leave off the period at the end of this sentence – I don't think we include it elsewhere, and it has [stern connotations with a growing number of English speakers](https://www.npr.org/transcripts/747020219). @javieralaves: thoughts?

2020-01-08 17:54 UTC, chadoh commented on app/src/App.js
> +      </Main>
The `SideContent` and `Main` are basically the same between this early return and the main return, but that's really hard to see now. If we change `SideContent` in one spot, we will also need to change it in the other, and it will be easy to forget that and end up with bugs.

2020-01-08 17:54 UTC, chadoh commented on app/src/App.js
>      entries &&
We know that `entries` is always defined now. We can remove this first check.

Also, why define `widgetList` up here, rather than inline? It's only used in one place.

2020-01-08 17:55 UTC, chadoh commented on app/src/App.js
> +                  members of your organization.
This is still a relevant question, even though GitHub marks it as outdated. The line moved, but the period is still there. Should we remove it, @javieralaves?

2020-01-08 17:58 UTC, e18r commented
@chadoh I remember this happened already in the past at some point where I think we introduced a Wrapper component around some shared logic. I'm gonna check it out and let you know.

2020-01-08 19:10 UTC, e18r commented
I sort of tracked down the origin of the side panel appearing without animation. It's something so unrelated to this PR, that I think it's worth creating a separate issue.

2020-01-08 19:37 UTC, chadoh submitted a review, later dismissed

2020-01-09 16:04 UTC, chadoh commented on app/src/App.js
> +                  members of your organization.
I've removed the period now, so I'm happy with this PR

2020-01-09 18:06 UTC, ottodevs commented
This PR was merged into #47

2020-01-09 18:06 UTC, closed without merging